# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: ViDoe - Visualizing Design of Experiments
author: Leonardo H. Talero-Sarmiento, Henry Lamos-Diaz, Juan D. Marquez-Gonzalez
logo: INGENIERÍA-INDUSTRIAL_LOGO.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Sphinx/BibTeX configuration: numeric, unsorted bibliography + author-year inline
sphinx:
  config:
    # choose one of: alpha, plain, unsrt, unsrtalpha
    bibtex_default_style: unsrt

    # choose one of: label, super, author_year
    bibtex_reference_style: author_year

# Your BibTeX file
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://eitt.github.io/DOE/intro.html
  path_to_book: docs
  branch: master

# Add GitHub buttons to your book
html:
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: true
